version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3"

  apt_packages:
    - make
    - gettext

  commands:
    - git clone https://github.com/FIRST-Tech-Challenge/ftcdocs.git venv/ftcdocs
    - python -m pip install --upgrade pip setuptools
    - python -m pip install -r venv/ftcdocs/docs/requirements.txt
    - make
    - mkdir -p _readthedocs/html/
    - cp -r venv/ftcdocs/docs/build/html/* _readthedocs/html/
